def getMolParams(mol,levels='all'):
    """
    Return numbered parameters for molecules in the molecular line databases of interest
    """

    #Dictionary of molecular parameters
    param_dict = {
        'CO': {'lamdamol': 'co', 
               'id': 5, 
               'iso': 1, 
               'groundState': '              0',
               'includeLevels':['              1'],
               'species': None},
        'CS': {'lamdamol': 'cs@lique',
               'id': 46,
               'iso': 1,
               'groundState': '              0',
               'includeLevels': ['              1'],
               'species': None},
        'HCN': {'lamdamol': 'hcn',
                'id': 23,
                'iso': 1,
                'groundState': '        0 0 0 0',
                'includeLevels': ['        1 0 0 0','        0 1 1 0','        0 2 0 0'],
                'species': None},
        'aCH3OH': {'lamdamol': 'a-ch3oh',
                   'id': 39,
                   'iso': 1,
                   'groundState': '         GROUND',
                   'includeLevels': ['           4V12','             V7','             V8'],
                   'species': 'A'},
        'eCH3OH': {'lamdamol': 'a-ch3oh',
                   'id': 39,
                   'iso': 1,
                   'groundState': '         GROUND',
                   'includeLevels': ['           3V12','             V7','             V8'],
                   'species': 'E'},
        'oH2CO': {'lamdamol': 'oh2co-h2',
                  'id': 20,
                  'iso': 1,
                  'groundState': '    0 0 0 0 0 0',
                  'includeLevels': ['    0 1 0 0 0 0','    0 0 1 0 0 0','    0 0 0 0 0 1'],
                  'species': None},
        'pH2CO': {'lamdamol': 'ph2co-h2',
                  'id': 20,
                  'iso': 1,
                  'groundState': '    0 0 0 0 0 0',
                  'includeLevels': ['    0 1 0 0 0 0','    0 0 1 0 0 0','    0 0 0 0 0 1'],
                  'species': None},
        'oH2O': {'lamdamol': 'oh2o@daniel',
                 'id': 1,
                 'iso': 1,
                 'groundState': '          0 0 0',
                 'includeLevels': ['          0 0 1','          0 1 0','          1 0 0','          1 0 1','          0 1 1'],
                 'species': None},
        'pH2O': {'lamdamol': 'ph2o@daniel',
                 'id': 1,
                 'iso': 1,
                 'groundState': '          0 0 0',
                 'includeLevels': ['          0 0 1','          0 1 0','          1 0 0','          1 0 1','          0 1 1'],
                 'species': None},
        'HNC': {'lamdamol': 'hnc',
                'id': None,
                'iso': None,
                'groundState': '                  0 0 0 0',
                'includeLevels': ['                  0 0 0 1','                  0 2 0 0','                  0 1 1 0','                  1 0 0 0'],
                'species': None},
        'oNH3': {'lamdamol': 'o-nh3',
                 'id': 11,
                 'iso': 1,
                 'includeLevels': [" 0000 00 0 A1' ", ' 0100 00 0 A2" ', " 0100 00 0 A1' ", " 0200 00 0 A1' ", " 0300 00 0 A1' ", " 0002 00 0 A1' ", ' 0002 00 0 A2" ', " 1000 00 0 A1' ", " 1100 00 0 A1' "],
                 'groundState': ' 0000 00 0 A2" ',
                 'species': None},
        'pNH3': {'lamdamol': 'p-nh3',
                 'id': 11,
                 'iso': 1,
                 'includeLevels': [" 0000 00 0 A1' ", ' 0100 00 0 A2" ', " 0100 00 0 A1' ", " 0200 00 0 A1' ", " 0300 00 0 A1' ", " 0002 00 0 A1' ", ' 0002 00 0 A2" ', " 1000 00 0 A1' ", " 1100 00 0 A1' ", " 0020 00 0 A1' "],
                 'groundState': ' 0000 00 0 A2" ',
                 'species': None}    
    }

    if levels == 'all':
        includeLevels = None
        return param_dict[mol]['lamdamol'], param_dict[mol]['id'], param_dict[mol]['iso'], includeLevels, param_dict[mol]['groundState'], param_dict[mol]['species']
    else:
        return param_dict[mol]['lamdamol'], param_dict[mol]['id'], param_dict[mol]['iso'], param_dict[mol]['includeLevels'], param_dict[mol]['groundState'], param_dict[mol]['species']
