def getMolParams(mol,levels='all'):
    """
    Return numbered parameters for molecules in the molecular line databases of interest
    """

    #Dictionary of molecular parameters
    param_dict = {
        'CO': {'lamdamol': 'co', 
               'cdms': '028503 CO',
               'id': 5, 
               'iso': 1, 
               'groundState': '              0',
               'includeLevels':['              1'],
               'species': None},
        'CS': {'lamdamol': 'cs@lique',
               'cdms': '044501 CS',
               'id': 46,
               'iso': 1,
               'groundState': '              0',
               'includeLevels': ['              1'],
               'species': None},
        'C34S': {'cdms': '046501 C34S',
               'id': 46,
               'iso': 2,
               'groundState': '              0',
               'includeLevels': ['              1'],
               'species': None},
        '13CS': {'cdms': '045501 13CS',
               'id': 46,
               'iso': 3,
               'groundState': '              0',
               'includeLevels': ['              1'],
               'species': None},
        'C33S': {'cdms': '045502 C33S',
               'id': 46,
               'iso': 4,
               'groundState': '              0',
               'includeLevels': ['              1'],
               'species': None},
        'HCN': {'lamdamol': 'hcn',
                'cdms': '027501 HCN',
                'id': 23,
                'iso': 1,
                'groundState': '        0 0 0 0',
                'includeLevels': ['        1 0 0 0','        0 1 1 0','        0 2 0 0'],
                #'includeLevels': ['        1 0 0 0'],
                'species': None},
        'HCN_hfs': {'lamdamol': 'hcn',
                'cdms': '027501_hfs HCN',
                'id': 23,
                'iso': 1,
                'groundState': '        0 0 0 0',
                'includeLevels': ['        1 0 0 0','        0 1 1 0','        0 2 0 0'],
                #'includeLevels': ['        1 0 0 0'],
                'species': None},
        'aCH3OH': {'lamdamol': 'a-ch3oh',
                   'id': 39,
                   'iso': 1,
                   'groundState': '         GROUND',
                   'includeLevels': ['           4V12','             V7','             V8'],
                   'species': 'A'},
        'eCH3OH': {'lamdamol': 'a-ch3oh',
                   'id': 39,
                   'iso': 1,
                   'groundState': '         GROUND',
                   'includeLevels': ['           3V12','             V7','             V8'],
                   'species': 'E'},
        'CH3OH': {'cdms': '032504 CH3OH',
                   'id': 39,
                   'iso': 1,
                   'groundState': '         GROUND',
                   'includeLevels': ['           4V12','           3V12','             V7','             V8'],
                   'species': None},
        'oH2CO': {'lamdamol': 'oh2co-h2',
                  'id': 20,
                  'iso': 1,
                  'groundState': '    0 0 0 0 0 0',
                  'includeLevels': ['    0 1 0 0 0 0','    0 0 1 0 0 0','    0 0 0 0 0 1'],
                  'species': None},
        'pH2CO': {'lamdamol': 'ph2co-h2',
                  'id': 20,
                  'iso': 1,
                  'groundState': '    0 0 0 0 0 0',
                  'includeLevels': ['    0 1 0 0 0 0','    0 0 1 0 0 0','    0 0 0 0 0 1'],
                  'species': None},
        'H2CO': {'cdms': '030501 H2CO',
                  'id': 20,
                  'iso': 1,
                  'groundState': '    0 0 0 0 0 0',
                  'includeLevels': ['    0 1 0 0 0 0','    0 0 1 0 0 0','    0 0 0 0 0 1'],
                  'species': None},
        'oH2O': {'lamdamol': 'oh2o@daniel',
                 'id': 1,
                 'iso': 1,
                 'groundState': '          0 0 0',
                 'includeLevels': ['          0 0 1','          0 1 0','          1 0 0','          1 0 1','          0 1 1'],
                 'species': None},
        'pH2O': {'lamdamol': 'ph2o@daniel',
                 'id': 1,
                 'iso': 1,
                 'groundState': '          0 0 0',
                 'includeLevels': ['          0 0 1','          0 1 0','          1 0 0','          1 0 1','          0 1 1'],
                 'species': None},
        'H2O': {'jpl': '18003 H2O',
                 'id': 1,
                 'iso': 4,
                 'groundState': '          0 0 0',
                 'includeLevels': ['          0 0 1','          0 1 0','          1 0 0','          1 0 1','          0 1 1'],
                 'species': None},
        'HDO': {'jpl': '19002 HDO',
                 'id': 1,
                 'iso': 2,
                 'groundState': '          0 0 0',
                 'includeLevels': ['          0 0 1','          0 1 0','          1 0 0','          1 0 1','          0 1 1'],
                 'species': None},
        'HNC': {'lamdamol': 'hnc',
                'cdms': '027502 HNC',
                'id': None,
                'iso': None,
                'groundState': '                  0 0 0 0',
                'includeLevels': ['                  0 0 0 1','                  0 2 0 0','                  0 1 1 0','                  1 0 0 0'],
                'species': None},
        'oNH3': {'lamdamol': 'o-nh3',
                 'id': 11,
                 'iso': 1,
                 'includeLevels': [" 0000 00 0 A1' ", ' 0100 00 0 A2" ', " 0100 00 0 A1' ", " 0200 00 0 A1' ", " 0300 00 0 A1' ", " 0002 00 0 A1' ", ' 0002 00 0 A2" ', " 1000 00 0 A1' ", " 1100 00 0 A1' "],
                 'groundState': ' 0000 00 0 A2" ',
                 'species': None},
        'pNH3': {'lamdamol': 'p-nh3',
                 'id': 11,
                 'iso': 1,
                 'includeLevels': [" 0000 00 0 A1' ", ' 0100 00 0 A2" ', " 0100 00 0 A1' ", " 0200 00 0 A1' ", " 0300 00 0 A1' ", " 0002 00 0 A1' ", ' 0002 00 0 A2" ', " 1000 00 0 A1' ", " 1100 00 0 A1' ", " 0020 00 0 A1' "],
                 'groundState': ' 0000 00 0 A2" ',
                 'species': None},
        'NH3': {'cdms': '017506 NH3',
                 'id': 11,
                 'iso': 1,
                 'includeLevels': [" 0000 00 0 A1' ", ' 0100 00 0 A2" ', " 0100 00 0 A1' ", " 0200 00 0 A1' ", " 0300 00 0 A1' ", " 0002 00 0 A1' ", ' 0002 00 0 A2" ', " 1000 00 0 A1' ", " 1100 00 0 A1' ", " 0020 00 0 A1' "],
                 'groundState': ' 0000 00 0 A2" ',
                 'species': None},
        'SO2': {'cdms': '064502 SO2',
                'id': 9,
                'iso': 1,
                'groundState': '          0 0 0',
                'species': None},
        '34SO2': {'cdms': '066501 34SO2',
                'id': 9,
                'iso': 2,
                'groundState': '          0 0 0',
                'species': None},
         'SO': {'cdms': '048501 SO',
                'id': 50,
                'iso': 1,
                'groundState': '       X      0',
                'species': None},  
         '34SO': {'cdms': '050501 34SO',
                'id': 50,
                'iso': 2,
                'groundState': '       X      0',
                'species': None}, 
         'OCS': {'cdms': '060503 OCS',
                'id': 19,
                'iso': 1,
                'groundState': '        0 0 0 0',
                'species': None},  
         'SiO': {'cdms': '044505 SiO',
                'id': 19,
                'iso': 1,
                'groundState': '        0 0 0 0',
                'species': None},  
         'HC3N': {'cdms': '051501 HC3N',
                'id': 44,
                'iso': 1,
                'groundState': '  0000000 0 0 0',
                'species': None}, 
         'CH3CN': {'cdms': '041505 CH3CN',
                'id': 41,
                'iso': 1,
                'groundState': '         GROUND' ,
                'species': None},
         'HCOOH': {'cdms': '046506 t-HCOOH',
                'id': 32,
                'iso': 1,
                'groundState': '         GROUND' ,
                'species': None},                     
    }

    if levels == 'all':
        includeLevels = None
        return param_dict[mol]['cdms'], param_dict[mol]['id'], param_dict[mol]['iso'], includeLevels, param_dict[mol]['groundState'], param_dict[mol]['species']
    else:
        return param_dict[mol]['cdms'], param_dict[mol]['id'], param_dict[mol]['iso'], param_dict[mol]['includeLevels'], param_dict[mol]['groundState'], param_dict[mol]['species']
